name: dko
channels:
- trelau
- peterjc123
- conda-forge
- alubbock
- anaconda
- dlr-sc
- defaults
dependencies:
- python=3.8.5
- pandas>=1.1.0
- scipy>=1.5.0
- scikit-learn>=0.23.1
- matplotlib>=3.3.0
- cython>=0.29.21


# prefix: C:\Miniconda37-x64\envs\transistor

# updated 8/2/2020